-- Run this in Supabase > SQL Editor
begin;

create table if not exists public.name_poll_votes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  first_choice text not null,
  second_choice text not null,
  third_choice text not null,
  reject_choice text,
  comment text
);

alter table public.name_poll_votes enable row level security;

-- Explicit privileges work even when automatic table exposure is disabled.
-- Limit callers to vote fields so they cannot supply IDs or timestamps.
revoke all on public.name_poll_votes from public, anon, authenticated;
grant usage on schema public to anon;
grant insert (first_choice, second_choice, third_choice, reject_choice, comment)
  on public.name_poll_votes to anon;
grant usage on sequence public.name_poll_votes_id_seq to anon;

-- Allow anyone with the public publishable key to submit a valid vote.
drop policy if exists "Anyone can submit a poll vote" on public.name_poll_votes;
create policy "Anyone can submit a poll vote"
on public.name_poll_votes
for insert
to anon
with check (
  first_choice in (
    'Protean','Manifold','Morphic','Emergent',
    'Liminal','Versant','Alchemic','All-Purpose Apps'
  )
  and second_choice in (
    'Protean','Manifold','Morphic','Emergent',
    'Liminal','Versant','Alchemic','All-Purpose Apps'
  )
  and third_choice in (
    'Protean','Manifold','Morphic','Emergent',
    'Liminal','Versant','Alchemic','All-Purpose Apps'
  )
  and first_choice <> second_choice
  and first_choice <> third_choice
  and second_choice <> third_choice
  and (
    reject_choice is null
    or reject_choice in (
      'Protean','Manifold','Morphic','Emergent',
      'Liminal','Versant','Alchemic','All-Purpose Apps'
    )
  )
  and (
    reject_choice is null
    or reject_choice not in (first_choice, second_choice, third_choice)
  )
  and (comment is null or length(comment) <= 240)
);

commit;

-- IMPORTANT:
-- There is intentionally NO anonymous SELECT policy.
-- Visitors can submit votes but cannot read everyone else's data.
-- You can view/export results from your authenticated Supabase dashboard.

-- Helpful analysis query:
-- 3 points for first, 2 for second, 1 for third.
with scores as (
  select first_choice as name, 3 as points from public.name_poll_votes
  union all
  select second_choice, 2 from public.name_poll_votes
  union all
  select third_choice, 1 from public.name_poll_votes
),
rejections as (
  select reject_choice as name, count(*) as rejects
  from public.name_poll_votes
  where reject_choice is not null
  group by reject_choice
)
select
  scores.name,
  sum(scores.points) as weighted_score,
  count(*) filter (where scores.points = 3) as first_place_votes,
  coalesce(rejections.rejects, 0) as rejects
from scores
left join rejections on rejections.name = scores.name
group by scores.name, rejections.rejects
order by weighted_score desc, first_place_votes desc;
